FROM node:alpine
WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .

CMD npm start

# building an image
# docker build -f Dockerfile.dev -t reactdevenv .

# creating a container
# docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/app reactdevenv